version: '3.8'

services:
  # web:
  #   build: .
  #   container_name: my-app
  #   ports:
  #     - "8000:8000"
  #   networks:
  #     - my-network
  #   depends_on:
  #     - redis
  redis:
      image: redis:latest
      container_name: my-redis
      ports:
        - "6379:6379"